### ISSUE TITLE
Install-Package PropertyGridHelpers  Successful installation , But, it was not successfully using?

### ISSUE THREAD

**Issue by AtlantisDe** [dparvin/PropertyGridHelpers#1]
## Install
```c#
Install-Package PropertyGridHelpers -Version 2020.8.7.3
```

**Comment by dparvin** [comment]
Sorry, I am in the middle of changing the package so it has 3 different versions of the DLL in it and during that process, it looks like I changed the package so it does not get any copy of the DLL installed.  I am hoping to get the process working so it has the three versions in the package file today.

**Comment by dparvin** [comment]
I have checked in a sample project in the source code that uses the actual package from NuGet.  Let me know if there is something that I can help you understand for using this tool.
